/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("pl.kamil.hrv.java-application-conventions")
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:3.1.5")
    runtimeOnly(project(":heartbeat-service"))
    runtimeOnly(project(":device-api"))
}

application {
    // Define the main class for the application.
    mainClass.set("pl.kamil.hrv.app.App")
}
