/*
 * This file was generated by the Gradle 'init' task.
 */


plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("pl.kamil.hrv.java-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

dependencies{
    implementation("org.springframework:spring-tx")
    implementation("org.springframework:spring-context")
    implementation("com.fasterxml.jackson.core:jackson-databind")
    testImplementation("org.springframework:spring-test")
}