/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.kamil.hrv.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
